### ISSUE TITLE
inconsistent bicgstb return value

### ISSUE THREAD

**Issue by maartenvd** [lruthotto/KrylovMethods.jl#15]
Hi

I generally use bicgstb as (retval,bicgflag,err)=bicgstb(x->f(x),b,...). However, when b is zero this causes errors as on line 41 in bicgstab.jl "if norm(b)==0; return zeros(eltype(b),n),-9; end" no error is returned.
I probably shouldn't attempt to solve for b=0 but it would be nice if that line was changed to
"if norm(b)==0; return zeros(eltype(b),n),-9,0,0,0; end" so that the return value matches the documentation even when norm(b) is zero.

Maarten

**Comment by lruthotto** [comment]
don't see a disadvantage of changing the return argument as suggested. would you like to make a PR for this? might take me a few days otherwise.
